services:
  devops-toolkit:
    image: foxonconsulting/devops-toolkit:1.0.1
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./:/app
      - ./key:/home/user/key
      - ~/.aws:/root/.aws
    container_name: "nextjs_website_cn"
    restart: unless-stopped
    command: bash -c "while true; do sleep 1; done"
